### ISSUE TITLE
publish() only accepts keyword arguments

### ISSUE THREAD

**Issue by wobeng** [cevoaustralia/aws-backup-lambda#7]
`Connecting to SNS
publish() only accepts keyword arguments.: TypeError
Traceback (most recent call last):
  File "/var/task/backuplambda.py", line 487, in lambda_handler
    sns_boto.publish(error_sns_arn, 'Error in processing RDS: ' + backup_mgr.errmsg, 'Error with AWS Snapshot')
  File "/var/runtime/botocore/client.py", line 308, in _api_call
    "%s() only accepts keyword arguments." % py_operation_name)
TypeError: publish() only accepts keyword arguments.`

**Comment by wobeng** [comment]
fixed in #8

**Comment by stevemac007** [comment]
Thanks for fixing this one too - we had the same issue in the EC2, but totally missed this was broken in RDS too.
